# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-99c7ca4f-0fe1-472b-bbdb-ade696fe4860";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-99c7ca4f-0fe1-472b-bbdb-ade696fe4860".device = "/dev/disk/by-uuid/99c7ca4f-0fe1-472b-bbdb-ade696fe4860";
  boot.initrd.luks.devices."luks-8cd2efb4-39e1-4b26-9531-b62bedad3d6c".device = "/dev/disk/by-uuid/8cd2efb4-39e1-4b26-9531-b62bedad3d6c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/89A6-7749";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8cd2efb4-39e1-4b26-9531-b62bedad3d6c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
