# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # disable panel self-refresh
  boot.kernelParams = [ "i915.enable_psr=0" ];

  # enable throttled for cpu throttle bug
  # services.throttled.enable = true;
  # services.throttled.extraConfig = ''
  #   [GENERAL]
  #   # Enable or disable the script execution
  #   Enabled: True
  #   Autoreload: True

  #   [AC]
  #   Update_Rate_s: 30

  #   ## Settings to apply while connected to Battery power
  #   [BATTERY]
  #   Update_Rate_s: 30
  #   # Disable BDPROCHOT (EXPERIMENTAL)
  #   Disable_BDPROCHOT: True
  # '';

  environment.systemPackages = with pkgs; [
    msr-tools
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7c4cc89a-b86c-4b8e-9886-4bd2e1ac3395";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."luks-5bb2e3be-8059-4e79-9816-1b3038380b6c".device =
    "/dev/disk/by-uuid/5bb2e3be-8059-4e79-9816-1b3038380b6c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/790D-CAEF";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/ae0c8149-bd94-4ef1-860d-b8883386f9f6"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20f0u3i12.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
