{ pkgs
, ...
}:
let
  i3Pkg = pkgs.i3;

  i3Config = pkgs.writeText "config"
  ''
    # This file has been auto-generated by i3-config-wizard(1).
    # It will not be overwritten, so edit it as you like.
    #
    # Should you change your keyboard layout somewhen, delete
    # this file and re-run i3-config-wizard(1).
    #

    # i3 config file (v4)
    #
    # Please see http://i3wm.org/docs/userguide.html for a complete reference!

    set $mod Mod1

    # font for window titles. ISO 10646 = Unicode
    #font -misc-fixed-medium-r-normal--14-120-75-75-C-70-iso10646-1
    font -*-terminus-*-*-*-*-12-*-*-*-*-*-*-16

    workspace_auto_back_and_forth yes

    # Use Mouse+$mod to drag floating windows to their wanted position
    floating_modifier $mod

    # start a terminal
    bindsym $mod+Return exec urxvtc

    # lock the screen
    bindsym $mod+Control+l exec i3lock -c 000000
    bindsym XF86ScreenSaver exec i3lock -c 000000

    # kill focused window
    bindsym $mod+Shift+C kill

    # start dmenu (a program launcher)
    bindsym $mod+p exec dmenu_run

    bindsym $mod+Tab workspace back_and_forth
    bindsym $mod+semicolon workspace back_and_forth

    # change focus
    bindsym $mod+h focus left
    bindsym $mod+j focus down
    bindsym $mod+k focus up
    bindsym $mod+l focus right

    # workspace next/prev
    bindsym XF86Forward workspace next_on_output
    bindsym XF86Back workspace prev_on_output
    #bindsym XF86Back exec i3lock -c 000000

    # move focused window
    bindsym $mod+Shift+H move left
    bindsym $mod+Shift+J move down
    bindsym $mod+Shift+K move up
    bindsym $mod+Shift+L move right

    # alternatively, you can use the cursor keys:
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

    # split in horizontal orientation
    bindsym $mod+Shift+V split h

    # split in vertical orientation
    bindsym $mod+v split v

    # enter fullscreen mode for the focused container
    bindsym $mod+f fullscreen

    # change container layout (stacked, tabbed, default)
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout default

    # toggle tiling / floating
    bindsym $mod+Shift+space floating toggle

    # change focus between tiling / floating windows
    bindsym $mod+space focus mode_toggle

    # focus the parent container
    bindsym $mod+a focus parent

    # focus the child container
    bindsym $mod+d focus child

    # switch to workspace
    bindsym $mod+1 workspace number 1:www
    bindsym $mod+2 workspace number 2:comm
    bindsym $mod+3 workspace number 3:mus
    bindsym $mod+4 workspace number 4:dev
    bindsym $mod+5 workspace number 5:mail
    bindsym $mod+6 workspace number 6
    bindsym $mod+7 workspace number 7
    bindsym $mod+8 workspace number 8
    bindsym $mod+9 workspace number 9:irc
    bindsym $mod+0 scratchpad show

    # move focused container to workspace
    bindsym $mod+Shift+exclam move container to workspace number 1:www
    bindsym $mod+Shift+at move container to workspace number 2:comm
    bindsym $mod+Shift+numbersign move container to workspace number 3:mus
    bindsym $mod+Shift+dollar move container to workspace number 4:dev
    bindsym $mod+Shift+percent move container to workspace number 5:mail
    bindsym $mod+Shift+asciicircum move container to workspace number 6
    bindsym $mod+Shift+ampersand move container to workspace number 7
    bindsym $mod+Shift+asterisk move container to workspace number 8
    bindsym $mod+Shift+parenleft move container to workspace number 9:irc
    bindsym $mod+Shift+parenright move scratchpad

    # mpd
    bindsym $mod+Control+z exec mpc prev
    bindsym $mod+Control+x exec mpc play
    bindsym $mod+Control+c exec mpc toggle
    bindsym $mod+Control+v exec mpc stop
    bindsym $mod+Control+b exec mpc next

    # mixer
    bindsym XF86AudioLowerVolume exec amixer -q set Master 1%-
    bindsym XF86AudioRaiseVolume exec amixer -q set Master 1%+
    bindsym XF86AudioMute exec amixer -q set Master toggle

    # reload the configuration file
    #bindsym $mod+Shift+C reload
    # restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
    bindsym $mod+Shift+R restart
    # exit i3 (logs you out of your X session)
    bindsym $mod+Shift+Q exit

    # resize window (you can also use the mouse for that)
    mode "resize" {
            # These bindings trigger as soon as you enter the resize mode

            # They resize the border in the direction you pressed, e.g.
            # when pressing left, the window is resized so that it has
            # more space on its left

    bindsym j resize shrink left 10 px or 10 ppt
    bindsym Shift+J resize grow   left 10 px or 10 ppt

    bindsym k resize shrink down 10 px or 10 ppt
    bindsym Shift+K resize grow   down 10 px or 10 ppt

    bindsym l resize shrink up 10 px or 10 ppt
    bindsym Shift+L resize grow   up 10 px or 10 ppt

    bindsym semicolon resize shrink right 10 px or 10 ppt
    bindsym Shift+colon resize grow   right 10 px or 10 ppt

            # same bindings, but for the arrow keys
    bindsym Left resize shrink left 10 px or 10 ppt
    bindsym Shift+Left resize grow   left 10 px or 10 ppt

    bindsym Down resize shrink down 10 px or 10 ppt
    bindsym Shift+Down resize grow   down 10 px or 10 ppt

    bindsym Up resize shrink up 10 px or 10 ppt
    bindsym Shift+Up resize grow   up 10 px or 10 ppt

    bindsym Right resize shrink right 10 px or 10 ppt
    bindsym Shift+Right resize grow   right 10 px or 10 ppt


            # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
    }

    #bindsym $mod+r mode "resize"
    bindsym $mod+r exec i3-input -F 'rename workspace to "%s"' -P 'New name: '

    bindsym $mod+u [urgent="latest"] focus
    bindsym $mod+b border toggle

    bindsym XF86MonBrightnessDown exec light -U 10%
    bindsym XF86MonBrightnessUp exec light -A 10%

    for_window [class="Dwb"] border none
    for_window [class="Google-chrome"] border none
    for_window [class="Chromium"] border none
    for_window [class="Firefox"] border none
    for_window [class="URxvt"] border none
    for_window [class="Riot"] border none
    for_window [class="Spotify"] border none

    exec nm-applet
    exec urxvtd
    exec xsetroot -solid darkgrey

    # Start i3bar to display a workspace bar (plus the system information i3status
    # finds out, if available)
    bar {
      status_command i3status
    #status_command i3status
                    position top
      colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
      }
    }
    client.focused #0088CC #0088CC #ffffff #dddddd
    client.focused_inactive #333333 #333333 #888888 #292d2e
    client.unfocused #333333 #333333 #888888 #292d2e
    client.urgent #2f343a #900000 #ffffff #900000
  '';

  xdgDir = pkgs.linkFarm "i3-config" [
    {
      name = "i3/config";
      path = i3Config;
    }
  ];

  i3Wrapped = pkgs.symlinkJoin {
    name = "i3";
    paths = [ i3Pkg ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram $out/bin/i3 \
      --set XDG_CONFIG_HOME "${xdgDir}"
      '';
  };
in
{
  config = {
    environment.systemPackages = [ i3Wrapped ];
  };
}
